### ISSUE TITLE
运行问题挺多org.elasticsearch.transport.RemoteTransportException: [SP08H4q][127.0.0.1:9300][indices:data/write/index[p]]

### ISSUE THREAD

**Issue by duxingren945** [medcl/elasticsearch-rtf#63]
使用 POST index/fulltext/_mapping
{
  "properties": {
      "content": {
          "type": "text",
          "analyzer": "ik_smart",
          "search_analyzer": "ik_smart"
      }
  }
}
上边命令创建成功index索引，然后添加一条文档时出现问题

POST index/fulltext/1
{"content":"美国留给伊拉克的是个烂摊子吗"}

错误提示如下：
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[SP08H4q][127.0.0.1:9300][indices:data/write/index[p]]"
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}

es的logs里显示：
[2017-09-06T14:38:06,324][WARN ][r.suppressed             ] path: /index/fulltext/1, params: {index=index, id=1, type=fulltext}
### org.elasticsearch.transport.RemoteTransportException: [SP08H4q][127.0.0.1:9300][indices:data/write/index[p]]
Caused by: java.lang.NullPointerException
	at org.wltea.analyzer.dic.Dictionary.isStopWord(Dictionary.java:334) ~[?:?]
	at org.wltea.analyzer.core.AnalyzeContext.getNextLexeme(AnalyzeContext.java:316) ~[?:?]
	at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:95) ~[?:?]
	at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:88) ~[?:?]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:712) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:417) ~[lucene-core-6.3.0.jar:6.3.0

**Comment by medcl** [comment]
配置文件修改过吗？

**Comment by duxingren945** [comment]
又重新配置了包，现在可以了
