### ISSUE TITLE
启动elasticsearch-rtf报错

### ISSUE THREAD

**Issue by TruthLiu** [medcl/elasticsearch-rtf#65]
[2017-09-21T13:24:23,142][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: No match found
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536) ~[?:1.8.0_111]
	at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:213) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:402) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:454) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:345) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more

**Comment by TruthLiu** [comment]
elasticsearch5.1.1.jar中的org/elasticsearch/monstor/os中的OsProbe.class用elasticsearch5.6.1.jar中的OsProbe.class来替换，就可以启动elasticsearch了

**Comment by medcl** [comment]
请问是在什么环境下测试的呢？

**Comment by kilingzhang** [comment]
如楼上同样错误
环境：
`version[5.1.1]`
`OS[Linux/4.9.0-deepin13-amd64/amd64]`
`JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b15]`

换了`OsProbe.class`文件就可以了

**Comment by MjSeven** [comment]
请问这个该怎么换呢？这些文件都在哪？新手提问

**Comment by MjSeven** [comment]
报如下错误，该怎么解决，哪些文件都在哪里？新手不太清楚
[2018-05-16T11:58:25,704][INFO ][o.e.p.PluginsService     ] [tS13pOF] loaded plugin [store-smb]                                        
[2018-05-16T11:58:26,081][WARN ][d.m.attachment           ] [mapper-attachments] plugin has been deprecated and will be replaced by [in
] plugin.                                                                                                                              
[2018-05-16T11:58:26,722][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]                   
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value           
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]                     
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]                  
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]                       
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]

**Comment by MjSeven** [comment]
新手报如下错误，跟上面那位有一点不一样 `Cannot create PyString with non-byte value ` ，怎么解决？还有那些文件都在哪里替换？      
```
[2018-05-16T11:58:25,704][INFO ][o.e.p.PluginsService     ] [tS13pOF] loaded plugin [store-smb]                                        
[2018-05-16T11:58:26,081][WARN ][d.m.attachment           ] [mapper-attachments] plugin has been deprecated and will be replaced by [in
] plugin.                                                                                                                              
[2018-05-16T11:58:26,722][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]                   
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot create PyString with non-b
org.elasticsearch.bootstrap.startupexception: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value           
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]                     
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]                  
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]                       
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]      
```

**Comment by MjSeven** [comment]
找到解决方法了，插件中的 lang-python 删除即可，估计是因为要加载 jython ，而我的电脑中没有这个环境，所以启动不起来
